import { MetricsDictionaryWithSelector } from "@tw/types/module/metrics/benchmarkMetrics";
import { metrics as allMetrics } from "./allMetrics";

export const supportedMetrics: MetricsDictionaryWithSelector = {
  "facebook-ads": {
    cpa: {
      ...allMetrics.cpa!,
      selector: "facebookCpaBenchmarksTotal",
      chart: "facebookCpaBenchmarksChart",
      provider: "facebook-ads",
      userSelector: "facebookCpa",
      userChart: "facebookCpaChart",
      tip: "Facebook Cost per Acquisition. Spend / Purchases",
    },
    cpc: {
      ...allMetrics.cpc!,
      selector: "facebookCpcBenchmarksTotal",
      chart: "facebookCpcBenchmarksChart",
      provider: "facebook-ads",
      userSelector: "averageFacebookCpc",
      userChart: "chartFacebookCpc",
      tip: "Facebook Cost per Click. Spend / Clicks",
    },
    roas: {
      ...allMetrics.roas!,
      selector: "facebookRoasBenchmarksTotal",
      chart: "facebookRoasBenchmarksChart",
      provider: "facebook-ads",
      userSelector: "fb_ads_purchase_roas",
      userChart: "chartFacebookPurchaseRoas",
      tip: "Facebook Return on Ad Spend. Conversion Value / Spend",
    },
    cpm: {
      ...allMetrics.cpm!,
      selector: "facebookCpmBenchmarksTotal",
      chart: "facebookCpmBenchmarksChart",
      provider: "facebook-ads",
      userSelector: "averageFacebookCpm",
      userChart: "chartFacebookCpm",
      tip: "Facebook Cost per Mile [ Cost per 1,000 impressions ]. (Spend / Impressions) * 1,000.",
    },
  },
  "google-ads": {
    cpa: {
      ...allMetrics.cpa!,
      selector: "googleCpaBenchmarksTotal",
      chart: "googleCpaBenchmarksChart",
      provider: "google-ads",
      userSelector: "googleAllCpa",
      userChart: "googleAllCpaChart",
      tip: "Google Cost per Acquisition. Spend / Purchases",
    },
    cpc: {
      ...allMetrics.cpc!,
      selector: "googleCpcBenchmarksTotal",
      chart: "googleCpcBenchmarksChart",
      provider: "google-ads",
      userSelector: "googleCpc",
      userChart: "googleCpcChart",
      tip: "Google Cost per Click. Spend / Clicks",
    },
    roas: {
      ...allMetrics.roas!,
      selector: "googleRoasBenchmarksTotal",
      chart: "googleRoasBenchmarksChart",
      provider: "google-ads",
      userSelector: "ga_ROAS",
      userChart: "googleAdsRoasChart",
      tip: "Google Return on Ad Spend. Conversion Value / Spend",
    },
    cpm: {
      ...allMetrics.cpm!,
      selector: "googleCpmBenchmarksTotal",
      chart: "googleCpmBenchmarksChart",
      provider: "google-ads",
      userSelector: "totalGoogleAdsCpm",
      userChart: "totalGoogleAdsCpmChart",
      tip: "Google Ads Cost per Mile [ Cost per 1,000 impressions ]. (Spend / Impressions) * 1,000.",
    },
  },
  "tiktok-ads": {
    cpa: {
      ...allMetrics.cpa!,
      selector: "tiktokCpaBenchmarksTotal",
      chart: "tiktokCpaBenchmarksChart",
      provider: "tiktok-ads",
      userSelector: "tiktokCpa",
      userChart: "tiktokCpaChart",
      tip: "Tiktok Cost per Acquisition. Spend / Purchases",
    },

    cpc: {
      ...allMetrics.cpc!,
      selector: "tiktokCpcBenchmarksTotal",
      chart: "tiktokCpcBenchmarksChart",
      provider: "tiktok-ads",
      userSelector: "averageTiktokCpc",
      userChart: "chartTiktokCpc",
      tip: "tiktok Cost per Click. Spend / Clicks",
    },
    roas: {
      ...allMetrics.roas!,
      selector: "tiktokRoasBenchmarksTotal",
      chart: "tiktokRoasBenchmarksChart",
      provider: "tiktok-ads",
      userSelector: "tiktokRoas",
      userChart: "tiktokRoasChart",
      tip: "Tiktok Return on Ad Spend. Conversion Value / Spend",
    },
    cpm: {
      ...allMetrics.cpm!,
      selector: "tiktokCpmBenchmarksTotal",
      chart: "tiktokCpmBenchmarksChart",
      provider: "tiktok-ads",
      userSelector: "averageTiktokCpm",
      userChart: "chartTiktokCpm",
      tip: "Tiktok Cost per Mile [ Cost per 1,000 impressions ]. (Spend / Impressions) * 1,000.",
    },
  },
  "triple-whale": {
    blendedCpa: {
      ...allMetrics.blendedCpa!,
      selector: "blendedCpaBenchmarksTotal",
      chart: "blendedCpaBenchmarksChart",
      provider: "triple-whale",
      tip: "Blended Cost per Acquisition. Spend / Purchases",
    },
    blendedCPC: {
      ...allMetrics.blendedCPC!,
      selector: "blendedCpcBenchmarksTotal",
      chart: "blendedCpcBenchmarksChart",
      provider: "triple-whale",
      tip: "Blended Cost per Click. Spend / Clicks",
    },
    blendedRoas: {
      ...allMetrics.blendedRoas!,
      selector: "blendedRoasBenchmarksTotal",
      chart: "blendedRoasBenchmarksChart",
      provider: "triple-whale",
      color: "#10B981",
      tip: "Blended Return on Ad Spend. Conversion Value / Spend",
    },
    blendedCpm: {
      ...allMetrics.blendedCpm!,
      selector: "blendedCpmBenchmarksTotal",
      chart: "blendedCpmBenchmarksChart",
      provider: "triple-whale",
      tip: "Blended Cost per Mile [ Cost per 1,000 impressions ]. (Spend / Impressions) * 1,000.",
    },
  },
};

export const colorsMetrics = ["#10B981", "#EA643D", "#B0446A", "#3159F3"];
