export type AmazonAdsEntityProps = {
  id: number;
  name: string;
  resource_name: string;
  status?: number;
  tracking_url_template?: string;
  final_url_suffix?: string;
};

export type AmazonAdsRawFile = {
  report: AmazonAdsSpReportEntry[] | AmazonAdsSbReportEntry[] | AmazonAdsSdReportEntry[];
  adAccount: AmazonAdAccount;
};
export type AmazonAdsReportType = 'sp' | 'sb' | 'sd';
export type AmazonAdAccount = {
  id: number;
  marketplaceId: string;
  sellerId: string;
  reportType: AmazonAdsReportType;
  timezone: string;
  // name: string;
  // currency: string;
};

export interface AmazonAdsSpReportEntry {
  adGroupId: number;
  adGroupName: string;
  campaignBudgetAmount?: number;
  campaignBudgetCurrencyCode: string;
  campaignBudgetType?: string;
  campaignId: number;
  campaignName: string;
  campaignStatus: string;
  clicks: number;
  clickThroughRate: number;
  cost: number;
  costPerClick: number;
  date: string;
  impressions: number;
  spend: number;
  purchases1d: number;
  purchasesSameSku1d: number;
  sales1d: number;
  unitsSoldClicks1d: number;
  unitsSoldSameSku1d: number;
  attributedSalesSameSku1d: number;
  purchases7d: number;
  purchasesSameSku7d: number;
  sales7d: number;
  unitsSoldClicks7d: number;
  unitsSoldSameSku7d: number;
  attributedSalesSameSku7d: number;
  purchases14d: number;
  purchasesSameSku14d: number;
  sales14d: number;
  unitsSoldClicks14d: number;
  unitsSoldSameSku14d: number;
  attributedSalesSameSku14d: number;
  purchases30d: number;
  purchasesSameSku30d: number;
  sales30d: number;
  unitsSoldClicks30d: number;
  unitsSoldSameSku30d: number;
  attributedSalesSameSku30d: number;
  adId: number;
  advertisedAsin: string;
  advertisedSku: string;
  acosClicks7d: number;
  acosClicks14d: number;
  roasClicks7d: number;
  roasClicks14d: number;
}

export interface AmazonAdsSbReportEntry {
  date: string;
  adGroupId: number;
  adGroupName: string;
  adId: number;
  applicableBudgetRuleId: number;
  applicableBudgetRuleName: string;
  attributedConversions14d: number;
  attributedConversions14dSameSKU: number;
  attributedDetailPageViewsClicks14d: number;
  attributedOrderRateNewToBrand14d: number;
  attributedOrdersNewToBrand14d: number;
  attributedOrdersNewToBrandPercentage14d: number;
  attributedSales14d: number;
  attributedSales14dSameSKU: number;
  attributedSalesNewToBrand14d: number;
  attributedSalesNewToBrandPercentage14d: number;
  attributedUnitsOrderedNewToBrand14d: number;
  attributedUnitsOrderedNewToBrandPercentage14d: number;
  campaignBudget: number;
  campaignBudgetType?: string;
  campaignId: number;
  campaignName: string;
  campaignRuleBasedBudget?: string;
  campaignStatus: string;
  clicks: number;
  cost: number;
  dpv14d: number;
  impressions: number;
  vctr: number;
  video5SecondViewRate: number;
  video5SecondViews: number;
  videoCompleteViews: number;
  videoFirstQuartileViews: number;
  videoMidpointViews: number;
  videoThirdQuartileViews: number;
  videoUnmutes: number;
  viewableImpressions: number;
  vtr: number;
  attributedBrandedSearches14d: number;
  currency: string;
}

export interface AmazonAdsSdReportEntry {
  date: string;
  adGroupId: number;
  adGroupName: string;
  adId: number;
  asin: string;
  attributedConversions14d: number;
  attributedConversions14dSameSKU: number;
  attributedConversions1d: number;
  attributedConversions1dSameSKU: number;
  attributedConversions30d: number;
  attributedConversions30dSameSKU: number;
  attributedConversions7d: number;
  attributedConversions7dSameSKU: number;
  attributedDetailPageView14d: number;
  attributedOrdersNewToBrand14d: number;
  attributedSales14d: number;
  attributedSales14dSameSKU: number;
  attributedSales1d: number;
  attributedSales1dSameSKU: number;
  attributedSales30d: number;
  attributedSales30dSameSKU: number;
  attributedSales7d: number;
  attributedSales7dSameSKU: number;
  attributedSalesNewToBrand14d: number;
  attributedUnitsOrdered14d: number;
  attributedUnitsOrdered1d: number;
  attributedUnitsOrdered30d: number;
  attributedUnitsOrdered7d: number;
  attributedUnitsOrderedNewToBrand14d: number;
  campaignId: number;
  campaignName: string;
  clicks: number;
  cost: number;
  currency: string;
  impressions: number;
  sku: string;
  viewAttributedConversions14d: number;
  viewImpressions: number;
  viewAttributedDetailPageView14d: number;
  viewAttributedSales14d: number;
  viewAttributedUnitsOrdered14d: number;
  viewAttributedOrdersNewToBrand14d: number;
  viewAttributedSalesNewToBrand14d: number;
  viewAttributedUnitsOrderedNewToBrand14d: number;
  attributedBrandedSearches14d: number;
  viewAttributedBrandedSearches14d: number;
  videoCompleteViews: number;
  videoFirstQuartileViews: number;
  videoMidpointViews: number;
  videoThirdQuartileViews: number;
  videoUnmutes: number;
  vtr: number;
  vctr: number;
}
