export enum FeatureFlag {

  /** 2.0 */
  AD_BUILDER_FF = 'AD_BUILDER_FF',
  CART_ANALYSIS_FF = 'CART_ANALYSIS_FF',
  CC_CREATIVE_ANALYSIS_FF = 'CC_CREATIVE_ANALYSIS_FF',
  CC_CREATIVE_HUB_FF = 'CC_CREATIVE_HUB_FF',
  CUSTOM_METRICS_FF = 'CUSTOM_METRICS_FF',
  CUSTOMERS_PAGE_FF = 'CUSTOMERS_PAGE_FF',
  EXPENSES_ACCESS_FF = 'EXPENSES_ACCESS_FF', // deprecated
  EXPORT_TO_SHEETS_FF = 'EXPORT_TO_SHEETS_FF',
  EXTERNAL_API_FF = 'EXTERNAL_API_FF',
  FINHUB_FF = 'FINHUB_FF',// deprecated
  INSIGHT_GENERAL_FF = 'INSIGHT_GENERAL_FF',
  LIGHTHOUSE_FF = 'LIGHTHOUSE_FF',
  LIMIT_CUSTOM_METRICS_FF = 'LIMIT_CUSTOM_METRICS_FF',// deprecated
  LIMIT_METRICS_FF = 'LIMIT_METRICS_FF',//hybrid?
  LIMIT_PIXEL_COLUMNS_FF = 'LIMIT_PIXEL_COLUMNS_FF',
  LIMIT_SUMMARY_SECTIONS_FF = 'LIMIT_SUMMARY_SECTIONS_FF',
  ORDERS_PAGE_FF = 'ORDERS_PAGE_FF',
  PIXEL_ALL_FF = 'PIXEL_ALL_FF',
  PIXEL_CHANNEL_OVERLAP_FF = 'PIXEL_CHANNEL_OVERLAP_FF',
  PIXEL_EMAIL_FF = 'PIXEL_EMAIL_FF',
  PIXEL_LIVE_ORDERS_FF = 'PIXEL_LIVE_ORDERS_FF',
  PIXEL_ORGANIC_FF = 'PIXEL_ORGANIC_FF',
  PIXEL_PURCHASE_POPUP_FF = 'PIXEL_PURCHASE_POPUP_FF',
  POST_PURCHASE_SURVEY_FF = 'POST_PURCHASE_SURVEY_FF',// deprecated
  PRODUCT_ANALYTICS_FF = 'PRODUCT_ANALYTICS_FF',
  SEGMENTATION_FF = 'SEGMENTATION_FF',
  SUMMARY_PAGE_FF = 'SUMMARY_PAGE_FF',
  USE_NEW_DESIGN_FF = 'USE_NEW_DESIGN_FF',// deprecated
  STORE_DATA_FF = 'STORE_DATA_FF',

  /** hybrid */
  SCDP_PAGE_FF = 'SCDP_PAGE_FF',
  SHIPPING_PAGE_FF = 'SHIPPING_PAGE_FF',
  PAYMENT_GATEWAY_COSTS_PAGE_FF = 'PAYMENT_GATEWAY_COSTS_PAGE_FF',
  LIMIT_INTEGRATIONS_FF = 'LIMIT_INTEGRATIONS_FF',
  FORECASTING_FF = 'FORECASTING_FF',
  FORECASTING_MENU_FF = 'FORECASTING_MENU_FF',
  FB_ADVANCED_BREAKDOWN_FF = 'FB_ADVANCED_BREAKDOWN_FF', // deprecated
  ACTIVITY_FEED_FF = 'ACTIVITY_FEED_FF',
  LIMIT_LOOKBACK_FF = 'LIMIT_LOOKBACK_FF',
  COGS_PAGE_FF = 'COGS_PAGE_FF',
  CUSTOM_EXPENSES_FF = 'CUSTOM_EXPENSES_FF',
  SPENDS_PAGE_FF = 'SPENDS_PAGE_FF',
  EMAIL_SLACK_REPORT_FF = 'EMAIL_SLACK_REPORT_FF',
  COST_SETTINGS_FF = 'COST_SETTINGS_FF',
  HUBSPOT_MEETING_FF = 'HUBSPOT_MEETING_FF',
  INVITE_USER_LIMIT_FF = 'INVITE_USER_LIMIT_FF',
  LIMIT_NOTIFICATIONS_FF = 'LIMIT_NOTIFICATIONS_FF',
  PIXEL_AFFLUENCER_HUB_FF = 'PIXEL_AFFLUENCER_HUB_FF',
  API_KEYS_FF = 'API_KEYS_FF',
  LIMIT_ROUTES_FF = 'LIMIT_ROUTES_FF',
  ADVANCED_BREAKDOWN_FF = 'ADVANCED_BREAKDOWN_FF',


  /** 3.0 */
  TEMPLATES_FF = 'TEMPLATES_FF',
  WILLY_CHAT_FF ='WILLY_CHAT_FF', // deprecated, use CHAT_FF
  PIXEL_CAPI_FF = 'PIXEL_CAPI_FF',
  WILLY_DEFAULT_TEMPLATES_FF = 'WILLY_DEFAULT_TEMPLATES_FF',
  TW_3_0_FF = 'TW_3_0_FF',
  TW_ONLY_3_0_FF = 'TW_ONLY_3_0_FF',
  CHAT_FF = 'CHAT_FF',
  SQL_FF = 'SQL_FF',
  MULTI_GEO_FF = 'MULTI_GEO_FF',
  WAREHOUSE_SYNC_FF = 'WAREHOUSE_SYNC_FF',
  CSV_EXPORTING_FF = 'CSV_EXPORTING_FF',
  AD_MANAGEMENT_FF = 'AD_MANAGEMENT_FF',
  METRIC_LIBRARY_CALCULATED_METRIC_FF = 'METRIC_LIBRARY_CALCULATED_METRIC_FF',
}
