export enum events {
  CREDENTIALS_ADD = 'CREDENTIALS_ADD',
  CREDENTIALS_UPDATE = 'CREDENTIALS_UPDATE',
  CREDENTIALS_DELETE = 'CREDENTIALS_DELETE',
  INTEGRATION_ADD = 'INTEGRATION_ADD',
  INTEGRATION_DELETE = 'INTEGRATION_DELETE',
  INTEGRATION_STATUS_UPDATE = 'INTEGRATION_STATUS_UPDATE',
  INTEGRATIONS_CHANGE = 'INTEGRATIONS_CHANGE',
  BU_ADD = 'BU_ADD',
}
