import { subscriptionType } from '../../subscription-manager';

export declare type hubspotRequestFromSignup = {
  step?: number;
  email?: string;
  shopDomain?: string;
  plans?: string[];
  agencyUrl?: string;
  agencyName?: string;
  revenue?: string;
  accountType?: 'AGENCY' | 'BRAND';
  firstname?: string;
  lastname?: string;
  phone?: string;
  shopCount?: number;
  referrer?: string;
  payer?: 'Brand' | 'Agency';
  source?: 'SIGNUP' | 'SIGNUP-FREE';
  hs_contact_id?: string;
  hs_company_id?: string;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  utm_content?: string;
  utm_keyword?: string;
  fw_key?: string;
  isFW?: boolean;
  industry?: string;
  role?: string;
  company_source?: string;
  contact_source?: string;
  installed_via_shopify_app_store?: boolean;
  shopify_uninstalled_date?: string;
  shopify_connection_status?: string;
  subscription_type?: subscriptionType;
  ip__shopify__accepts_marketing?: boolean;
  login_method?: 'google' | 'facebook' | 'Username';
  agency_sign_up_link?: string;
  triple_whale_platform?: number;
};
