export const vatIds = [
  {
    COUNTRY: 'Andorra',
    ENUM: 'ad_nrt',
    DESCRIPTION: 'Andorran NRT number',
    EXAMPLE: 'A-123456-Z',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Argentina',
    ENUM: 'ar_cuit',
    DESCRIPTION: 'Argentinian tax ID number',
    EXAMPLE: '12-3456789-01',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Australia',
    ENUM: 'au_abn',
    DESCRIPTION: 'Australian Business Number (AU ABN)',
    EXAMPLE: '12345678912',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Australia',
    ENUM: 'au_arn',
    DESCRIPTION: 'Australian Taxation Office Reference Number',
    EXAMPLE: '123456789123',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Austria',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'ATU12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Belgium',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'BE0123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Bolivia',
    ENUM: 'bo_tin',
    DESCRIPTION: 'Bolivian tax ID',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Brazil',
    ENUM: 'br_cnpj',
    DESCRIPTION: 'Brazilian CNPJ number',
    EXAMPLE: '01.234.456/5432-10',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Brazil',
    ENUM: 'br_cpf',
    DESCRIPTION: 'Brazilian CPF number',
    EXAMPLE: '123.456.789-87',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Bulgaria',
    ENUM: 'bg_uic',
    DESCRIPTION: 'Bulgaria Unified Identification Code',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Bulgaria',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'BG0123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Canada',
    ENUM: 'ca_bn',
    DESCRIPTION: 'Canadian BN',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Canada',
    ENUM: 'ca_gst_hst',
    DESCRIPTION: 'Canadian GST/HST number',
    EXAMPLE: '123456789RT0002',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Canada',
    ENUM: 'ca_pst_bc',
    DESCRIPTION: 'Canadian PST number (British Columbia)',
    EXAMPLE: 'PST-1234-5678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Canada',
    ENUM: 'ca_pst_mb',
    DESCRIPTION: 'Canadian PST number (Manitoba)',
    EXAMPLE: '123456-7',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Canada',
    ENUM: 'ca_pst_sk',
    DESCRIPTION: 'Canadian PST number (Saskatchewan)',
    EXAMPLE: '1234567',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Canada',
    ENUM: 'ca_qst',
    DESCRIPTION: 'Canadian QST number (Québec)',
    EXAMPLE: '1234567890TQ1234',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Chile',
    ENUM: 'cl_tin',
    DESCRIPTION: 'Chilean TIN',
    EXAMPLE: '12.345.678-K',
    VALIDATION: null,
  },
  {
    COUNTRY: 'China',
    ENUM: 'cn_tin',
    DESCRIPTION: 'Chinese tax ID',
    EXAMPLE: '123456789012345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Colombia',
    ENUM: 'co_nit',
    DESCRIPTION: 'Colombian NIT number',
    EXAMPLE: '123.456.789-0',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Costa Rica',
    ENUM: 'cr_tin',
    DESCRIPTION: 'Costa Rican tax ID',
    EXAMPLE: '1-234-567890',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Croatia',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'HR12345678912',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Cyprus',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'CY12345678Z',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Czech Republic',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'CZ1234567890',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Denmark',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'DK12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Dominican Republic',
    ENUM: 'do_rcn',
    DESCRIPTION: 'Dominican RCN number',
    EXAMPLE: '123-4567890-1',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Ecuador',
    ENUM: 'ec_ruc',
    DESCRIPTION: 'Ecuadorian RUC number',
    EXAMPLE: '1234567890001',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Egypt',
    ENUM: 'eg_tin',
    DESCRIPTION: 'Egyptian Tax Identification Number',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'El Salvador',
    ENUM: 'sv_nit',
    DESCRIPTION: 'El Salvadorian NIT number',
    EXAMPLE: '1234-567890-123-4',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Estonia',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'EE123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'EU',
    ENUM: 'eu_oss_vat',
    DESCRIPTION: 'European One Stop Shop VAT number for non-Union scheme',
    EXAMPLE: 'EU123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Finland',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'FI12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'France',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'FRAB123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Georgia',
    ENUM: 'ge_vat',
    DESCRIPTION: 'Georgian VAT',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Germany',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'DE123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Greece',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'EL123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Hong Kong',
    ENUM: 'hk_br',
    DESCRIPTION: 'Hong Kong BR number',
    EXAMPLE: '12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Hungary',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'HU12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Hungary',
    ENUM: 'hu_tin',
    DESCRIPTION: 'Hungary tax number (adószám)',
    EXAMPLE: '12345678-1-23',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Iceland',
    ENUM: 'is_vat',
    DESCRIPTION: 'Icelandic VAT',
    EXAMPLE: '123456',
    VALIDATION: null,
  },
  {
    COUNTRY: 'India',
    ENUM: 'in_gst',
    DESCRIPTION: 'Indian GST number',
    EXAMPLE: '12ABCDE3456FGZH',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Indonesia',
    ENUM: 'id_npwp',
    DESCRIPTION: 'Indonesian NPWP number',
    EXAMPLE: '12.345.678.9-012.345',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Ireland',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'IE1234567AB',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Israel',
    ENUM: 'il_vat',
    DESCRIPTION: 'Israel VAT',
    EXAMPLE: '000012345',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Italy',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'IT12345678912',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Japan',
    ENUM: 'jp_cn',
    DESCRIPTION: 'Japanese Corporate Number (Hōjin Bangō)',
    EXAMPLE: '1234567891234',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Japan',
    ENUM: 'jp_rn',
    DESCRIPTION:
      "Japanese Registered Foreign Businesses' Registration Number (Tōroku Kokugai Jigyōsha no Tōroku Bangō)",
    EXAMPLE: '12345',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Japan',
    ENUM: 'jp_trn',
    DESCRIPTION: 'Japanese Tax Registration Number (Tōroku Bangō)',
    EXAMPLE: 'T1234567891234',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Kenya',
    ENUM: 'ke_pin',
    DESCRIPTION: 'Kenya Revenue Authority Personal Identification Number',
    EXAMPLE: 'P000111111A',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Latvia',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'LV12345678912',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Liechtenstein',
    ENUM: 'li_uid',
    DESCRIPTION: 'Liechtensteinian UID number',
    EXAMPLE: 'CHE123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Lithuania',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'LT123456789123',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Luxembourg',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'LU12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Malaysia',
    ENUM: 'my_frp',
    DESCRIPTION: 'Malaysian FRP number',
    EXAMPLE: '12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Malaysia',
    ENUM: 'my_itn',
    DESCRIPTION: 'Malaysian ITN',
    EXAMPLE: 'C 1234567890',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Malaysia',
    ENUM: 'my_sst',
    DESCRIPTION: 'Malaysian SST number',
    EXAMPLE: 'A12-3456-78912345',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Malta',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'MT12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Mexico',
    ENUM: 'mx_rfc',
    DESCRIPTION: 'Mexican RFC number',
    EXAMPLE: 'ABC010203AB9',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Netherlands',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'NL123456789B12',
    VALIDATION: null,
  },
  {
    COUNTRY: 'New Zealand',
    ENUM: 'nz_gst',
    DESCRIPTION: 'New Zealand GST number',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Norway',
    ENUM: 'no_vat',
    DESCRIPTION: 'Norwegian VAT number',
    EXAMPLE: '123456789MVA',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Peru',
    ENUM: 'pe_ruc',
    DESCRIPTION: 'Peruvian RUC number',
    EXAMPLE: '12345678901',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Philippines',
    ENUM: 'ph_tin',
    DESCRIPTION: 'Philippines Tax Identification Number',
    EXAMPLE: '123456789012',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Poland',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'PL1234567890',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Portugal',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'PT123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Romania',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'RO1234567891',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Romania',
    ENUM: 'ro_tin',
    DESCRIPTION: 'Romanian tax ID number',
    EXAMPLE: '1234567890123',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Russia',
    ENUM: 'ru_inn',
    DESCRIPTION: 'Russian INN',
    EXAMPLE: '1234567891',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Russia',
    ENUM: 'ru_kpp',
    DESCRIPTION: 'Russian KPP',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Saudi Arabia',
    ENUM: 'sa_vat',
    DESCRIPTION: 'Saudi Arabia VAT',
    EXAMPLE: '123456789012345',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Serbia',
    ENUM: 'rs_pib',
    DESCRIPTION: 'Serbian PIB number',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Singapore',
    ENUM: 'sg_gst',
    DESCRIPTION: 'Singaporean GST',
    EXAMPLE: 'M12345678X',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Singapore',
    ENUM: 'sg_uen',
    DESCRIPTION: 'Singaporean UEN',
    EXAMPLE: '123456789F',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Slovakia',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'SK1234567891',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Slovenia',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'SI12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Slovenia',
    ENUM: 'si_tin',
    DESCRIPTION: 'Slovenia tax number (davčna številka)',
    EXAMPLE: '12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'South Africa',
    ENUM: 'za_vat',
    DESCRIPTION: 'South African VAT number',
    EXAMPLE: '4123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'South Korea',
    ENUM: 'kr_brn',
    DESCRIPTION: 'Korean BRN',
    EXAMPLE: '123-45-67890',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Spain',
    ENUM: 'es_cif',
    DESCRIPTION: 'Spanish NIF number (previously Spanish CIF number)',
    EXAMPLE: 'A12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Spain',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'ESA1234567Z',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Sweden',
    ENUM: 'eu_vat',
    DESCRIPTION: 'European VAT number',
    EXAMPLE: 'SE123456789123',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Switzerland',
    ENUM: 'ch_vat',
    DESCRIPTION: 'Switzerland VAT number',
    EXAMPLE: 'CHE-123.456.789 MWST',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Taiwan',
    ENUM: 'tw_vat',
    DESCRIPTION: 'Taiwanese VAT',
    EXAMPLE: '12345678',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Thailand',
    ENUM: 'th_vat',
    DESCRIPTION: 'Thai VAT',
    EXAMPLE: '1234567891234',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Turkey',
    ENUM: 'tr_tin',
    DESCRIPTION: 'Turkish Tax Identification Number',
    EXAMPLE: '0123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Ukraine',
    ENUM: 'ua_vat',
    DESCRIPTION: 'Ukrainian VAT',
    EXAMPLE: '123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'United Arab Emirates',
    ENUM: 'ae_trn',
    DESCRIPTION: 'United Arab Emirates TRN',
    EXAMPLE: '123456789012345',
    VALIDATION: null,
  },
  {
    COUNTRY: 'United Kingdom',
    ENUM: 'eu_vat',
    DESCRIPTION: 'Northern Ireland VAT number',
    EXAMPLE: 'XI123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'United Kingdom',
    ENUM: 'gb_vat',
    DESCRIPTION: 'United Kingdom VAT number',
    EXAMPLE: 'GB123456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'United States',
    ENUM: 'us_ein',
    DESCRIPTION: 'United States EIN',
    EXAMPLE: '12-3456789',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Uruguay',
    ENUM: 'uy_ruc',
    DESCRIPTION: 'Uruguayan RUC number',
    EXAMPLE: '123456789012',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Venezuela',
    ENUM: 've_rif',
    DESCRIPTION: 'Venezuelan RIF number',
    EXAMPLE: 'A-12345678-9',
    VALIDATION: null,
  },
  {
    COUNTRY: 'Vietnam',
    ENUM: 'vn_tin',
    DESCRIPTION: 'Vietnamese tax ID number',
    EXAMPLE: '1234567890',
    VALIDATION: null,
  },
];
