export const ServicesIdsArray = [
  'facebook-ads',
  'google-ads',
  'tiktok-ads',
  'snapchat-ads',
  'pinterest-ads',
  'shopify',
  'shopify-segment',
  'google-analytics',
  'enquirelabs',
  'kno',
  'okendo',
  'benchmarks',
  'influencers',
  'stripe',
  'atlassian',
  'amazon',
  'pixel',
  'triple-whale',
  'twitter-ads',
  'bing',
  'skio',
  'recharge',
  'hubspot',
  'gorgias',
  'slack',
  'google-sheets',
  'mountain',
  'tatari',
  'criteo',
  'shipstation',
  'smsbump',
  'intercom',
  'shipbob',
  'postscript',
  'taboola',
  'adroll',
  'outbrain',
  'gcp',
  'posthog',
  'klaviyo',
  'woocommerce',
  'bigcommerce',
  'linkedin',
  'website-content',
  'pps',
  'tiktok-shops',
] as const;

export type ServicesIds = (typeof ServicesIdsArray)[number];

export type allServices = {
  [t in ServicesIds]?: t;
};

export const servicesRoles: allServices = {
  'facebook-ads': 'facebook-ads',
  'google-ads': 'google-ads',
  'tiktok-ads': 'tiktok-ads',
  'snapchat-ads': 'snapchat-ads',
  'pinterest-ads': 'pinterest-ads',
  'twitter-ads': 'twitter-ads',
  shopify: 'shopify',
  enquirelabs: 'enquirelabs',
  kno: 'kno',
  benchmarks: 'benchmarks',
  'google-analytics': 'google-analytics',
  influencers: 'influencers',
  stripe: 'stripe',
  'shopify-segment': 'shopify-segment',
  amazon: 'amazon',
  pixel: 'pixel',
  'triple-whale': 'triple-whale',
  bing: 'bing',
  recharge: 'recharge',
  hubspot: 'hubspot',
  gorgias: 'gorgias',
  slack: 'slack',
  'google-sheets': 'google-sheets',
  intercom: 'intercom',
  gcp: 'gcp',
  posthog: 'posthog',
  klaviyo: 'klaviyo',
  pps: 'pps',
  smsbump: 'smsbump',
};

export const supportedByNexus: ServicesIds[] = [
  'bing',
  // 'criteo',
  'twitter-ads',
  //'pinterest-ads',
  'tiktok-ads',
  'snapchat-ads',
  'google-ads',
  'facebook-ads',
];
